### ISSUE TITLE
About the COCO panoptic segmentation data

### ISSUE THREAD

**Issue by isksjsksk** [cp3wan/DFormer#3]
Hi,

I download  COCO panoptic segmentation datasets from COCO official website and fulfil the structure requirements. However when I run `python datasets/prepare_coco_semantic_annos_from_panoptic_annos.py` it reports an error:
```
Traceback (most recent call last):
  File "/mnt/c/Users/Administrator/Desktop/projects/DFormer-main/datasets/prepare_coco_semantic_annos_from_panoptic_annos.py", line 79, in <module>
    separate_coco_semantic_from_panoptic(
  File "/mnt/c/Users/Administrator/Desktop/projects/DFormer-main/datasets/prepare_coco_semantic_annos_from_panoptic_annos.py", line 68, in separate_coco_semantic_from_panoptic
    pool.starmap(
  File "/home/lcl/anaconda3/envs/pytorch/lib/python3.10/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/lcl/anaconda3/envs/pytorch/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/coco/panoptic_train2017/000000000540.png'
```
It is wierd that "000000000540.png" is not included in COCO panoptic segmentation and why here it is needed?
Then I try to train and it reports another similar error:
```
Traceback (most recent call last):
  File "/mnt/c/Users/Administrator/Desktop/projects/DFormer-main/train_net.py", line 321, in <module>
    launch(
  File "/mnt/c/Users/Administrator/Desktop/projects/DFormer-main/detectron2/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "/mnt/c/Users/Administrator/Desktop/projects/DFormer-main/train_net.py", line 313, in main
    trainer = Trainer(cfg)
  File "/mnt/c/Users/Administrator/Desktop/projects/DFormer-main/detectron2/detectron2/engine/defaults.py", line 378, in __init__
    data_loader = self.build_train_loader(cfg)
  File "/mnt/c/Users/Administrator/Desktop/projects/DFormer-main/train_net.py", line 170, in build_train_loader
    return build_detection_train_loader(cfg, mapper=mapper)
  File "/mnt/c/Users/Administrator/Desktop/projects/DFormer-main/detectron2/detectron2/config/config.py", line 207, in wrapped
    explicit_args = _get_args_from_config(from_config, *args, **kwargs)
  File "/mnt/c/Users/Administrator/Desktop/projects/DFormer-main/detectron2/detectron2/config/config.py", line 245, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/mnt/c/Users/Administrator/Desktop/projects/DFormer-main/detectron2/detectron2/data/build.py", line 420, in _train_loader_from_config
    dataset = get_detection_dataset_dicts(
  File "/mnt/c/Users/Administrator/Desktop/projects/DFormer-main/detectron2/detectron2/data/build.py", line 242, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
  File "/mnt/c/Users/Administrator/Desktop/projects/DFormer-main/detectron2/detectron2/data/build.py", line 242, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
  File "/mnt/c/Users/Administrator/Desktop/projects/DFormer-main/detectron2/detectron2/data/catalog.py", line 58, in get
    return f()
  File "/mnt/c/Users/Administrator/Desktop/projects/DFormer-main/detectron2/detectron2/data/datasets/coco_panoptic.py", line 88, in <lambda>
    lambda: load_coco_panoptic_json(panoptic_json, image_root, panoptic_root, metadata),
  File "/mnt/c/Users/Administrator/Desktop/projects/DFormer-main/detectron2/detectron2/data/datasets/coco_panoptic.py", line 62, in load_coco_panoptic_json
    assert PathManager.isfile(ret[0]["pan_seg_file_name"]), ret[0]["pan_seg_file_name"]
AssertionError: datasets/coco/panoptic_train2017/000000000009.png
```
 "000000000009.png" should also not be included in COCO panoptic segmentation task.

**Comment by isksjsksk** [comment]
Is the file that I download right?"[2017 Panoptic Train/Val annotations [821MB]](http://images.cocodataset.org/annotations/panoptic_annotations_trainval2017.zip)"
I have downloaded it many times and COCO2017 have 118287 pictures, but Panoptic datasets only provide 52751. I think that is the problem, so the official dataset is incomplete and where can I download the complete dataset?

**Comment by 0sillow** [comment]
you can find it in https://cocodataset.org/#explore
