### ISSUE TITLE
KeyError: 'Non-existent config key: MODEL.DFORMER' while running demo.py

### ISSUE THREAD

**Issue by Ustinian-J** [cp3wan/DFormer#7]
When I try to run demo.py as showed in README.md, a problem occurred.
Details:
```
Traceback (most recent call last):
  File "demo.py", line 106, in <module>
    cfg = setup_cfg(args)
  File "demo.py", line 39, in setup_cfg
    cfg.merge_from_file(args.config_file)
  File "/home/jxh/detectron2/detectron2/config/config.py", line 69, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "/home/jxh/anaconda3/envs/dformer/lib/python3.8/site-packages/fvcore/common/config.py", line 132, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)
  File "/home/jxh/anaconda3/envs/dformer/lib/python3.8/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/jxh/anaconda3/envs/dformer/lib/python3.8/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/jxh/anaconda3/envs/dformer/lib/python3.8/site-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))

KeyError: 'Non-existent config key: MODEL.DFORMER'
```
Thank you for your answers.

**Comment by Shillin123** [comment]
Hi, have you solved the issue? I also have this problem while running demo

**Comment by Shillin123** [comment]
> Hi, have you solved the issue? I also have this problem while running demo

I solved it, simply add "add_DFormer_config" to demo
